### ISSUE TITLE
Error on Category with Posts

### ISSUE THREAD

**Issue by davidshq** [surajprgupta/taxonomy-listing#3]
Receive the following error:

Notice: Array to string conversion in /home/toms/public_html/philcata.com/wp-content/plugins/taxonomy-listing-plugin/templates/template-parts/posts/list-item.php on line 43

See:

https://www.philcata.com/section/email/

WP Debug further notes:

NOTICE: wp-content/plugins/taxonomy-listing-plugin/templates/template-parts/posts/list-item.php:43 - Array to string conversion
require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/taxonomy-listing-plugin/templates/template-taxonomy.php'), SCRPTZ_TDL_Core::get_term_posts, Template_View_Loader::get_template, Template_View_Loader->load, include('/plugins/taxonomy-listing-plugin/templates/template-parts/posts/list.php'), SCRPTZ_TDL_Core::get_term_posts_list, Template_View_Loader::get_template, Template_View_Loader->load, include('/plugins/taxonomy-listing-plugin/templates/template-parts/posts/list-item.php')

**Comment by surajprgupta** [comment]
I think the error was occurring while accessing the `post_meta`, and it was solved in the last set of update files.
